env:
  contexts:
    - excludePaths: []
      name: baseline
      urls:
        - http://localhost:4100
  parameters:
    failOnError: false
    progressToStdout: true
jobs:
  - parameters:
      enableTags: false
      maxAlertsPerRule: 10
    type: passiveScan-config
  - parameters:
      maxDuration: 1
      url: http://localhost:4100
    type: spider
  - parameters:
      maxDuration: 0
    type: passiveScan-wait
  - parameters:
      format: Long
      summaryFile: /home/zap/zap_out.json
    rules: []
    type: outputSummary
  - parameters:
      reportDescription: "Baseline passive scan of Conduit application"
      reportDir: /zap/wrk/
      reportFile: zap-passive-report.html
      reportTitle: ZAP Baseline Scanning Report
      template: traditional-html
    type: report
